### PR TITLE
VCard search modifications

### PR DESCRIPTION
**Pull request by astro**
From OP-388:
- [x] Allow for empty search input
- [x] Filter by activated state
- [x] Add Result Set Management for pageing

### CODE REVIEW

**Comment by astro** [comment]
This is ready for review @nicolai86 @HugoMaster

**Comment by nicolai86** [comment]
Yay erlang! Will review once at work

**Comment by nicolai86** [comment]
LGTM, no questions to the erlang part. the travis tests were red, so I restarted them

**Comment by astro** [comment]
The preset we run is green.

I should restrict tests for the mod_vcard_mnesia modifications to the corresponding presets...

**Comment by astro** [comment]
The non-specific part has been sent upstream: https://github.com/esl/MongooseIM/pull/978

**Comment by nicolai86** [comment]
❤️

**Pull request merged**
